### PR TITLE
fix belongsTo relation

### PR DESCRIPTION
**Pull request by omidahn**
(change otherKey to ownerKey)

### CODE REVIEW

**Comment by mlanin** [comment]
Please, clean up your request.

**Comment by JoeyHoutenbos** [comment]
This doesn't seem to be fixed in the stable version yet?

**Comment by pi0** [comment]
@JoeyHoutenbos Another PR fixed this problem in dev-master and we are just using it in production. However more tests are needed to ensure everything is working fine before officially release 5.4 compatible version :)

**Comment by JoeyHoutenbos** [comment]
Thanks for your response. I just tried the dev-master and it seems to be working fine now  :)

**Comment by JoeyHoutenbos** [comment]
@pi0 I am getting this error `Call to undefined method Moloquent\Query\Builder::getBelongsToManyCaller()` when calling ```$menu->organisations()```.

The relationship in the menu-model is defined as:
```php
	public function organisations()
	{
		return $this->belongsToMany(Organisation::class);
	}
```

**Comment by pi0** [comment]
@JoeyHoutenbos I it seems another problem with `BelongsToMany` relations. Would you please open an issue for that? So we can investigate problem. Thanks.

**Comment by JoeyHoutenbos** [comment]
@pi0 It's also related to this, because the BelongsToMany class still uses the `otherKey` property, which no longer exists.

**Pull request closed without merging**
