### PR TITLE
Update DatabaseTokenRepository.php

### PR DESCRIPTION
**Pull request by thiagocarnaes**
Update in function getPayload in created_at 
Update in function tokenExpired, change the variable $token to $createdAt

### CODE REVIEW

**Comment by pi0** [comment]
Are you sure `hasher` is available in laravel <5.4-5.3 ?

**Comment by thiagocarnaes** [comment]
Before laravel 5.2 i don't know if hasher is available, but if I only use the variable $token, returns the message:
 "This password reset token is invalid.", 202

**Comment by pi0** [comment]
Can you please check [this](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php#L139) if we can easier implementation? If not it looks good to me.

**Comment by thiagocarnaes** [comment]
it works if i use like this

<?php

namespace Moloquent\Auth;

use Carbon\Carbon;
use DateTime;
use DateTimeZone;
use Illuminate\Auth\Passwords\DatabaseTokenRepository as BaseDatabaseTokenRepository;

class DatabaseTokenRepository extends BaseDatabaseTokenRepository
{
    /**
     * Build the record payload for the table.
     *
     * @param string $email
     * @param string $token
     *
     * @return array
     */
    protected function getPayload($email, $token)
    {
        return ['email' => $email, 'token' => $this->hasher->make($token), 'created_at' => new Carbon];
    }

    /**
     * Determine if the token has expired.
     *
     * @param array $createdAt
     *
     * @return bool
     */
    protected function tokenExpired($createdAt)
    {
        return Carbon::parse($createdAt['date'])->addSeconds($this->expires)->isPast();
    }
}

**Comment by pi0** [comment]
It seems better

**Pull request merged**
